Added site sampling to 1D raveller
geoschem/gcpy pull request #107
Opened 2021-02-10 20:26 UTC by LiamBindle

Added the ability to create a 1D track for sampling ground sites. For example

```console
$ python -m gcpy.raveller_1D create_site_track --csv /home/liam/Downloads/SPARTAN_sites.csv --samples_per_day 48 --separator "\t" -o spartan_sites.nc
```

where `SPARTAN_sites.csv` is a file like this (tab separator, specified by `--separator` argument and passed to pandas)
```
23.728	90.398	Dhaka
-6.888	107.610	Bandung
21.048	105.800	Hanoi
14.635	121.078	Manila
37.564	126.935	Seoul
40.004	116.326	Beijing
-25.75661	28.280	Pretoria
-34.555	-58.506	Buenos Aires
1.298	103.780	Singapore
44.638	-63.594	Halifax
43.790	-79.470	Toronto
26.513	80.232	Kanpur
8.484	4.675	Ilorin
31.907	34.811	Rehovot
45.380	-71.931	Sherbrooke
49.682	-112.869	Lethbridge
33.688	-84.290	Atlanta
49.941	-119.400	Kelowna
24.442	54.617	Abu Dhabi
37.132	-86.148	Mammoth Cave
40.053	-88.372	Bondville
4.637	-74.081	Palmira
```

2021-02-10 20:53 UTC, WilliamDowns commented on gcpy/raveller_1D.py
> +                              type=str,
Can you align these arguments with the ones from the other add_argument() calls?

2021-02-10 20:56 UTC, WilliamDowns requested changes
Can you change the target to `dev/1.0.3` instead of `main`?

2021-02-10 20:56 UTC, WilliamDowns commented on gcpy/raveller_1D.py
> +                              type=str,
Also here

2021-02-10 20:56 UTC, WilliamDowns commented on gcpy/raveller_1D.py
> +                              required=True,
Can you align these arguments with the ones from the other add_argument() calls?

2021-02-10 20:56 UTC, WilliamDowns commented
Oops, review comments out of order.

2021-04-24 20:51 UTC, closed without merging

2022-03-03 15:31 UTC, msulprizio commented
@LiamBindle What is the status of this update? Should we reopen this PR and merge into `dev`?