Abstract routines out of gcpy/plot.py into smaller modules within the gcpy/plot folder
geoschem/gcpy pull request #263
Opened 2023-09-21 19:42 UTC by yantosca

In this PR we have moved GCPy's plotting capability out of the monolithic module `gcpy/plot.py` into smaller modules in the `gcpy/plot` folder.  These are:

1. `gcpy/plot/core.py`: Contains common functions and definitions used by other plotting routines.

2. `gcpy/plot/single_panel.py`: Module containing the `single_panel` routine, which creates a single-panel plot.

3. `gcpy/plot/six_plot.py`: Module containing the `six_plot` routine (which calls `single_panel` 6 times to create a comparison plot), plus several helper functions that were abstracted and refactored for clarity.

4. `gcpy/plot/compare_single_level.py`: Module containing the `compare_single_level` routine (creates a 6-panel comparison plot at a single model level).

5. `gcpy/plot/compare_zonal_mean.py`: Module containing the `compare_zonal_mean` routine (creates a 6-panel comparison with zonal means).

6. `gcpy/plot/gcpy_plot_style`: Style sheet with several plot attribute settings (moved from the `gcpy/` folder).

7. `gcpy/plot/colormaps/`: Folder with colormap definitions (moved from `gcpy/colormaps`).

8. `gcpy/plot/__init__.py`: Import script

Import statements and other plot settings have now been updated accordingly in the following scripts:
- `gcpy/benchmark_funcs.py`
- `gcpy/examples/diagnostics/compare_diags.py`
- `gcpy/examples/plotting/plot_single_level.py`
- `gcpy/examples/plotting/plot_comparisons.py`
- `gcpy/examples/timeseries/mda8_o3_timeseries.py`

The plotting code in GCPy is now much cleaner and easier to understand.  Also, plotting-only functionality is now able to be abstracted from the benchmarking code.

I have confirmed that the benchmark plotting codes are able to run with these modifications.

2023-10-24 17:43 UTC, lizziel requested changes
This looks good to merge. I just added one comment on a typo I found in a comment.

2023-10-24 17:43 UTC, lizziel commented on gcpy/examples/diagnostics/compare_diags.py
> +    # Function to read thed data
typo

2023-10-24 18:24 UTC, yantosca commented
Also updated CHANGELOG.md to state that the `tk` package has been added to the environment.yml file.  This is so that we can use X11 backend `tkagg`.

2023-10-25 19:29 UTC, msulprizio approved these changes

2023-10-25 20:11 UTC, merged